<?php
/**
 * Plugin Name: HMS By PK
 * Description: Management of hospital made easy by us.
 * Version: 1.0.0
 * Author: Piyush Khandelwal
 */

// Prevent direct access to the file for security
defined( 'ABSPATH' ) or die('This page is not accessible by unauthorized users.');

/**
 * Define constants
 *
 * These constants are used throughout the plugin for paths, URLs, and file references.
 */

// Absolute path to the plugin directory
define( 'HMS_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

// URL to the plugin directory
define( 'HMS_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

// Path to the main plugin file
define( 'HMS_PLUGIN_MAIN_FILE', __FILE__ );

// Plugin name as defined in the WordPress plugins directory
define( 'HMS_PLUGIN_NAME', plugin_basename(__FILE__) );

define( 'HMS_USER_ROLES_PREDENCE', [
    'administrator' => 500,
    'hms_admin' => 400,
    'hms_doctor' => 300,
    'hms_staff' => 200,
    'hms_patient' => 100
] );

/**
 * Require the Composer Autoloader
 *
 * Ensures that all classes and dependencies are loaded automatically.
 * The autoloader is typically generated by Composer when dependencies are installed.
 */
require_once dirname( __FILE__ ) . '/vendor/autoload.php';

/**
 * Use the Initialize class
 *
 * This class is responsible for bootstrapping the plugin, such as registering hooks,
 * loading dependencies, and initializing key features.
 */
use HMS\Includes\Initialize;

// Check if the Initialize class exists before calling it
if ( class_exists( 'HMS\\Includes\\Initialize' ) ) {
    // Call the `init` method to initialize the plugin
    Initialize::class::init();
}
